### ISSUE TITLE
Remote Disconnected when gis.next_page()

### ISSUE THREAD

**Issue by aprofili** [arrrlo/Google-Images-Search#119]
Seemingly any time I make a call to `gis.next_page()` I get faced with the following:

```
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Adam/OneDrive/Documents/Classes/Fall 2021/LMC3259/Final Project/Code/scrape.py", line 48, in <module>
    gis.next_page()
  File "C:\ProgramData\Miniconda3\lib\site-packages\google_images_search\fetch_resize_save.py", line 217, in next_page
    self.search(*self._get_data())
  File "C:\ProgramData\Miniconda3\lib\site-packages\google_images_search\fetch_resize_save.py", line 151, in search
    self._search_images(*self._get_data())
  File "C:\ProgramData\Miniconda3\lib\site-packages\google_images_search\fetch_resize_save.py", line 177, in _search_images
    for url in self._google_custom_search.search(
  File "C:\ProgramData\Miniconda3\lib\site-packages\google_images_search\google_api.py", line 94, in search
    response = requests.head(
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 104, in head
    return request('head', url, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```
Can anybody make out what is going on? I can provide more info about my code if requested.

**Comment by aprofili** [comment]
Nevermind, I was being dumb
