### ISSUE TITLE
Error on Attempt

### ISSUE THREAD

**Issue by calebcarithers** [arrrlo/Google-Images-Search#38]
I am sure I am missing something here, but attempting to run 
```
from google_images_search import GoogleImagesSearch

gis = GoogleImagesSearch('omitted','omitted')
_search_params = {
    'q': 'dog',
    'num': 1,
    'safe': 'off'
}
gis.search(search_params=_search_params)
```

and am getting the following error

```
Traceback (most recent call last):
  File "/Users/calebcarithers/Desktop/Project_TBD/google_image_test.py", line 9, in <module>
    gis.search(search_params=_search_params)
  File "/Users/calebcarithers/Desktop/Project_TBD/venv/lib/python3.7/site-packages/google_images_search/fetch_resize_save.py", line 55, in search
    search_params, cache_discovery
  File "/Users/calebcarithers/Desktop/Project_TBD/venv/lib/python3.7/site-packages/google_images_search/google_api.py", line 79, in search
    for image in res.get('items'):
TypeError: 'NoneType' object is not iterable
```

**Comment by arrrlo** [comment]
Hey @calebcarithers,

will look into this and get back to you.

**Comment by arrrlo** [comment]
Just checked and it works for me:

```python
import unittest
from google_images_search import GoogleImagesSearch

class TestGoogleApi(unittest.TestCase):

    def setUp(self):
        self._api_key = 'omitted'
        self._api_cx = 'omitted'
        self._api = GoogleImagesSearch(self._api_key, self._api_cx)

    def test_init(self):
        _search_params = {
            'q': 'dog',
            'num': 1,
            'safe': 'off'
        }
        self._api.search(search_params=_search_params)

        for image in self._api.results():
            self.assertTrue(image.url.startswith('https://'))
```

```bash
======================================== test session starts ========================================
platform darwin -- Python 3.7.2, pytest-5.1.2, py-1.8.0, pluggy-0.12.0 -- /......./Google-Images-Search/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /....../Google-Images-Search
collected 1 item

tests/test_my.py::TestGoogleApi::test_init PASSED                                             [100%]
```

But will implement fix so your code doesn't break.
Will get to you soon.

**Comment by arrrlo** [comment]
Hey @calebcarithers,

A new version is out, 1.0.1.
Try it out and let me know if everything is ok.

**Comment by calebcarithers** [comment]
@arrrlo works like a charm! Thanks!
