### ISSUE TITLE
unable to import GoogleImagesSearch

### ISSUE THREAD

**Issue by sstephans** [arrrlo/Google-Images-Search#40]
this is my exact input/output. seems to be a more internal error?

`>>> from google_images_search import GoogleImagesSearch`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\saman\AppData\Local\Programs\Python\Python36\lib\site-packages\google_images_search\__init__.py", line 1, in <module>
    from google_images_search.fetch_resize_save import \
  File "C:\Users\saman\AppData\Local\Programs\Python\Python36\lib\site-packages\google_images_search\fetch_resize_save.py", line 2, in <module>
    import curses
  File "C:\Users\saman\AppData\Local\Programs\Python\Python36\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'`

**Comment by sendbeedev** [comment]
Hi @sstephans 

Looks like 12 **curses** module is not supported on Windows machines:
https://stackoverflow.com/a/35851229

**Comment by arrrlo** [comment]
Hi @sstephans 

Look like curses module is not supported on Windows machines.
https://stackoverflow.com/a/35851229

**Comment by sstephans** [comment]
ah, I guess that explains it. thanks!

**Comment by xiaoyongzhu** [comment]
Looks like there's a workaround in the stackoverflow thread above. 
`pip install windows-curses` works on my windows machine.

**Comment by MarcosOriolPago** [comment]
> Looks like there's a workaround in the stackoverflow thread above. `pip install windows-curses` works on my windows machine.

Thanks a lot! I had the same issue and this fixed it : )
