### ISSUE TITLE
ModuleNotFoundError: No module named '_curses' on Windows

### ISSUE THREAD

**Issue by anwar3606** [arrrlo/Google-Images-Search#89]
Getting this error when running in windows: 

```log
C:\Users\anwar\Desktop\gitlab-helper\venv\Scripts\python.exe C:/Users/anwar/Desktop/gitlab-helper/project-avatar-updater.py
Traceback (most recent call last):
  File "C:/Users/anwar/Desktop/gitlab-helper/project-avatar-updater.py", line 1, in <module>
    from google_images_search import GoogleImagesSearch
  File "C:\Users\anwar\Desktop\gitlab-helper\venv\lib\site-packages\google_images_search\__init__.py", line 1, in <module>
    from google_images_search.fetch_resize_save import \
  File "C:\Users\anwar\Desktop\gitlab-helper\venv\lib\site-packages\google_images_search\fetch_resize_save.py", line 2, in <module>
    import curses
  File "C:\Python38\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```
Used the demo on readme

**Comment by max4211** [comment]
https://github.com/pmbarrett314/curses-menu/issues/18#issuecomment-436070434

try `pip install windows-curses`

**Comment by arrrlo** [comment]
Hi @anwar3606,

Did you manage to solve this?

**Comment by anwar3606** [comment]
yes, this fixes things

**Comment by yang666-888** [comment]
How did you solve this problem bro? I've already been stack here for some days
